tab_spaces = 2
edition = "2021"
max_width = 120
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_modules = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Upper"
normalize_comments = true
normalize_doc_attributes = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
imports_granularity = "Module"
newline_style = "Unix"
